Jumia_MVC/Models/Pager.cs
namespace Jumia_MVC.Models
{
    public class Pager
    {
        public int TotalItems { get; private set; }
public int CurrentPage{get;private set;}
public int PageSize { get; private set; }
public int TotalPages { get; private set; }
    
public int StartPage { get; private set; }
    
public int EndPage { get; private set; }

        public Pager() { }
        public Pager(int totalItem,int page ,int pageSize=10) {

            int totalPage=(int) Math.Ceiling((decimal)totalItem/(decimal)pageSize);
            int currentPage = page;

            int startPage = currentPage - 5;
            int endPage = currentPage + 4;

            if(startPage <= 0)
            {
                endPage=endPage-(startPage-1);
                startPage=1;
            }

            if(endPage > totalPage)
            {
                endPage=totalPage;

                if (endPage > 10)
                {
                    startPage = endPage - 9;
                }
            }

            CurrentPage = currentPage;
            PageSize = pageSize;
            TotalPages = totalPage;
            StartPage = startPage;
            EndPage = endPage;
            TotalItems = totalItem;
        }
}
}

Jumia_MVC/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace Jumia_MVC.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Jumia_MVC/Controllers/BannerController.cs
namespace Jumia_MVC.Controllers
{

    public class BannerController : Controller
    {
        private readonly IBannerService _bannerService;

        public BannerController(IBannerService bannerService)
        {
            _bannerService = bannerService;
        }

        public async Task<IActionResult> Index()
        {
            var res =await _bannerService.GellAll();
            return View(res);
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            var category = await _bannerService.GetById(id);
            if (category == null) return View("NotFound");
            return View(category);

        }
        [HttpGet]

        public async Task<IActionResult> Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Banner banner)
        {
            if (!ModelState.IsValid) return View(banner);

            var res = new Banner()
            {
                Title = banner.Title,
                SubTitle = banner.SubTitle,
                Image = banner.Image,
            };
            await _bannerService.Add(res);
            return RedirectToAction(nameof(Index));

        }

        [HttpGet]

        public async Task<IActionResult> Edit(int id)
        {
            var res = await _bannerService.GetById(id);
            if (res == null) return View("NotFound");
            return View(res);

        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, Banner banner)
        {
            if (id != banner.Id) return View("NotFound");
            if (ModelState.IsValid)
            {
               await _bannerService.update(banner);
                return RedirectToAction(nameof(Index));

            }


            return View(banner);

        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            if (id == null)
            {
                return View("NotFound");

            }
            var res = await _bannerService.GetById(id);
            if (res == null)
            {
                return View("NotFound");
            }
            else
            {
                return View(res);
            }
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirm(int id)
        {
            if (id == null)
            {
                return View("NotFound");
            }

            var res = await _bannerService.GetById(id);
           await _bannerService.delete(res);
            return RedirectToAction(nameof(Index));

        }
    }
}

Jumia_MVC/Controllers/RoleController.cs
using FinalProject.MVC.Data.ViewModel;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Localization;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.EntityFrameworkCore;

namespace Jumia_MVC.Controllers
{
    //[Authorize(Roles = UserRole.Admin)]

    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;

        private readonly IHtmlLocalizer<RoleController> _localizer;


        public RoleController(RoleManager<IdentityRole> roleManager, IHtmlLocalizer<RoleController> localizer)
        {
            _roleManager = roleManager;
            _localizer = localizer;
        }
        public async Task<IActionResult> Index()
        {
            var roles = await _roleManager.Roles.ToListAsync();
            return View(roles);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Create(RoleFormViewModel model)
        {
            if (!ModelState.IsValid) return View("Index", await _roleManager.Roles.ToListAsync());

            var roleExist = await _roleManager.RoleExistsAsync(model.Name);

            if (await _roleManager.RoleExistsAsync(model.Name))
            {
                ModelState.AddModelError("Name", _localizer["exist"].ToString());
                return View("Index", await _roleManager.Roles.ToListAsync());
            }

            await _roleManager.CreateAsync(new IdentityRole(model.Name.Trim()));

            return RedirectToAction(nameof(Index));

        }
        public async Task<IActionResult> Edit(string  id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);

            return View(role);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, IdentityRole role)
        {
            var rolee = await _roleManager.FindByIdAsync(id);

            if (id != role.Id) return View("NotFound");

            //var roleExist = await _roleManager.RoleExistsAsync(role.Name);

            //if (await _roleManager.RoleExistsAsync(role.Name))
            //{
            //    ModelState.AddModelError("Name", "Role Is Exist !!!");
            //    return View("Index", await _roleManager.Roles.ToListAsync());
            //}

            rolee.Name = role.Name;

            await _roleManager.UpdateAsync(rolee);

            return RedirectToAction(nameof(Index));


        
        }

        public async Task<IActionResult> Delete(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            if (role != null)
            {
                IdentityResult result = await _roleManager.DeleteAsync(role);
                if (result.Succeeded)
                    return RedirectToAction("Index");
                else
                    View("NotFound");
            }
            else
                ModelState.AddModelError("", _localizer["wrong"].ToString());
            return View("Index", _roleManager.Roles);

        }

    }
}

Jumia_MVC/Views/Shared/CustomButton.cshtml
@model string;

    <div class="text-white" style="position:fixed; right:25px; bottom:25px;">
    <a  asp-action="Create" asp-controller="@Model" class="btn btn-success">
       <i class="bi bi-plus-circle"></i> Add New
    </a>
</div>
    

Jumia_MVC/Views/Shared/NotFound.cshtml
<div class="row">
    <div class="col-md-6 offset-3">
        <h1 class="text-info">You've reached the end of the internet</h1>
        <hr />
        <a class="btn btn-outline-success" asp-controller="Movie" asp-action="Index">Home Page</a>
    </div>
</div>

Jumia_MVC/Views/Shared/_Culture.cshtml
@using Microsoft.AspNetCore.Localization

@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer;
@inject Microsoft.Extensions.Options.IOptions<RequestLocalizationOptions> locOPtions;

@{
    var culture = Context.Features.Get<IRequestCultureFeature>();
    var cultureList = locOPtions.Value.SupportedCultures.Select(x => new SelectListItem{Value = x.Name, Text = localizer.GetString(x.Name)}).ToList();
    var returnUrl = string.IsNullOrWhiteSpace(Context.Request.Path) ? "~/" : $"~{Context.Request.Path.Value}{Context.Request.QueryString}";
}
<style>
    select{
        margin-top:4px;
        border:none;
        padding:4px;
    }

</style>

<div>
    <form asp-action="CultureManagement" asp-controller="Home" method="post" asp-route-returnUrl ="@returnUrl">
        <select name="culture" asp-for="@culture.RequestCulture.UICulture.Name" asp-items="cultureList" 
        onchange="this.form.submit();" ></select>
    </form>
</div>

Jumia_MVC/Views/Shared/_admin.cshtml
@inject UserManager<ApplicationUser> UserManager; 
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UseAdminPanel</title>
  @*  <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/UseAdminPanel.styles.css" asp-append-version="true" />*@
     <link rel="stylesheet" href="~/plugins/fontawesome-free/css/all.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Tempusdominus Bbootstrap 4 -->
  <link rel="stylesheet" href="~/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
  <!-- iCheck -->
  <link rel="stylesheet" href="~/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
  <!-- JQVMap -->
  <link rel="stylesheet" href="~/plugins/jqvmap/jqvmap.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="~/dist/css/adminlte.min.css">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="~/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
  <!-- Daterange picker -->
  <link rel="stylesheet" href="~/plugins/daterangepicker/daterangepicker.css">
  <!-- summernote -->
  <link rel="stylesheet" href="~/plugins/summernote/summernote-bs4.css">
  <!-- Google Font: Source Sans Pro -->
   <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EcommerceApp.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EcommerceApp.Web.styles.css" asp-append-version="true" />
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
     <link
  rel="stylesheet" href="https://unpkg.com/swiper@8/swiper-bundle.min.css"/>
     <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
      integrity="sha512-9usAa10IRO0HhonpyAIVpjrylPvoDwiPUiKdWk5t3PyolY1cOd4DSE0Ga+ri4AuTroPR5aQvXU9xC6qOPnzFeg=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
</head>
<body class="hold-transition sidebar-mini layout-fixed">
    
   <div class="wrapper">
         <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a asp-action="Index" asp-controller="Home"  class="nav-link">Home</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Contact</a>
      </li>
    </ul>

    <!-- SEARCH FORM -->
    <form class="form-inline ml-3" asp-controller="Product" asp-action="Filter">
      <div class="input-group input-group-sm">
        <input class="form-control form-control-navbar"  name="searchString" value="@TempData["serch"]" type="text" placeholder="Search" aria-label="Search">
        <div class="input-group-append">
          <button class="btn btn-navbar" type="submit">
            <i class="fas fa-search"></i>
          </button>
        </div>
      </div>
    </form>
                       

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Messages Dropdown Menu -->
         <partial name="IdentityView.cshtml" />

      <li class="nav-item">
        <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
          <i class="fas fa-th-large"></i>
        </a>
      </li>
    </ul>
  </nav>
  <!-- /.navbar -->
    <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a  class="brand-link">
      <img src="~/dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
           style="opacity: .8">
      <span class="brand-text font-weight-light">Admin Page</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="~/dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="#" class="d-block">@UserManager.GetUserName(User)</a>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
         
               <li class="nav-item">
            <a asp-action="Index" asp-controller="Product" class="nav-link">
         <i class="fa-brands fa-product-hunt"></i>
         <p>
                Product
                <span class="right badge badge-danger">New</span>
              </p>
            </a>
          </li>
       
            <li class="nav-item">
            <a asp-action="Index" asp-controller="Category" class="nav-link">
              <i class="nav-icon bi bi-app-indicator"></i>
              <p>
                Category
                <span class="right badge badge-danger">New</span>
              </p>
            </a>
          </li>
               <li class="nav-item">
            <a asp-action="Index" asp-controller="Banner" class="nav-link">
              <i class="fa-solid fa-images"></i>
              <p>
                Bannner
                <span class="right badge badge-danger">New</span>
              </p>
            </a>
          </li>
              <li class="nav-item">
            <a asp-action="Index" asp-controller="User" class="nav-link">
              <i class="nav-icon bi bi-people"></i>
              <p>
                User
                <span class="right badge badge-danger">New</span>
              </p>
            </a>
          </li>
               <li class="nav-item">
            <a asp-action="Index" asp-controller="Role" class="nav-link">
              <i class="fa-solid fa-registered"></i> 
              <p>
                Role
                <span class="right badge badge-danger">New</span>
              </p>
            </a>
          </li>
                 <li class="nav-item">
            <a asp-action="Index" asp-controller="Orders" class="nav-link">
              <i class="bi bi-list"></i> 
              <p>
                Orders
                <span class="right badge badge-danger">New</span>
              </p>
            </a>
          </li>
          
      
         
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>



  

    <div class="content-wrapper">
   

        <main role="main" class="content">
            <div class="container-fluid">
            @RenderBody()
             </div>

        </main> 

    </div>


   </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - UseAdminPanel - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>



<!-- jQuery -->
<script src="~/plugins/jquery/jquery.min.js"></script>
<!-- jQuery UI 1.11.4 -->
<script src="~/plugins/jquery-ui/jquery-ui.min.js"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- ChartJS -->
<script src="~/plugins/chart.js/Chart.min.js"></script>
<!-- Sparkline -->
<script src="~/plugins/sparklines/sparkline.js"></script>
<!-- JQVMap -->
<script src="~/plugins/jqvmap/jquery.vmap.min.js"></script>
<script src="~/plugins/jqvmap/maps/jquery.vmap.usa.js"></script>
<!-- jQuery Knob Chart -->
<script src="~/plugins/jquery-knob/jquery.knob.min.js"></script>
<!-- daterangepicker -->
<script src="~/plugins/moment/moment.min.js"></script>
<script src="~/plugins/daterangepicker/daterangepicker.js"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="~/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
<!-- Summernote -->
<script src="~/plugins/summernote/summernote-bs4.min.js"></script>
<!-- overlayScrollbars -->
<script src="~/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
<!-- AdminLTE App -->
<script src="~/dist/js/adminlte.js"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="~/dist/js/pages/dashboard.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="~/dist/js/demo.js"></script>

 <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
     <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <script src="~/lib/bootbox.js/bootbox.min.js"></script>
    <script src="https://unpkg.com/swiper@8/swiper-bundle.min.js"></script>

    <script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Jumia_MVC/Views/Shared/_footer.cshtml
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer;

<footer class="container-fluid mt-5   border-top footer text-muted " 
    dir="@(System.Threading.Thread.CurrentThread.CurrentCulture.TextInfo.IsRightToLeft? "rtl" : "ltr")">
    <div class="row ">
  
        <div class="col-md-3 col-12 my-3  text-dark text-center"> 
            <h3 class="text-start text-uppercase text-dark fw-bold  text-center"> 
            <img src="~/image/logo.png"> <span class=" mx-1" style="color:#f68b1e;">E-</span>SHOPE</h3>
            <p class="text-secondary">
                @localizer["footerDescription"]
            </p>
            <div class="my-3   d-flex justify-content-around ">
                <i class="fa-brands fa-facebook fa-2x text-secondary"></i>
                <i class="fa-brands fa-twitter fa-2x text-secondary"></i>
                <i class="fa-brands fa-instagram fa-2x text-secondary"></i>
                <i class="fa-brands fa-youtube fa-2x text-secondary"></i>
              </div>
        </div>
   
        <div class="col-12 col-md-3 my-3  text-dark text-center "> 
            <h3 class="text-start text-uppercase text-dark fw-bold  text-center"> @localizer["Navigation"]</h3>
         @*   <ul class="list-group">
                <li class="list-group-item-action text-secondary">@localizer["Home"] </li>
                <li class=" list-group-item-action text-secondary">@localizer["OurService"] </li>
                <li class="list-group-item-action text-secondary">@localizer["Feadback"]</li>
                <li class="list-group-item-action text-secondary ">@localizer["request"]</li>
            </ul>*@
            <ul class="list-unstyled">
                
                    <a class="nav-link text-dark" asp-controller="Home" asp-action="Index"> @localizer["Home"] </a> 
                    <a class="nav-link text-dark" asp-controller="Product" asp-action="Index">@localizer["Product"] </a>
                    <a class="nav-link text-dark" asp-controller="About" asp-action="Index" >@localizer["About"] </a>
                    <a class="nav-link text-dark" asp-controller="ContactUs"  asp-action="Index"> @localizer["ContactUs"] </a>
            </ul>
        </div>
  
        <div class="col-12 col-md-3 my-3  text-dark text-center "> 
            <h3 class="text-start text-uppercase text-dark fw-bold text-center"> @localizer["More"]</h3>
            <ul class="list-unstyled">
                <a class="nav-link text-dark" href="#">@localizer["FAQ`S"] </a>
                <a class="nav-link text-dark" href="#">@localizer["Privacy"] </a>
                <a class="nav-link text-dark" href="#">@localizer["Liscences"]  </a>


               @* <li class="list-group-item-action text-secondary">@localizer["FAQ`S"] </li>
                <li class="list-group-item-action text-secondary">@localizer["Privacy"] </li>
                <li class="list-group-item-action -text-secondary">@localizer["Liscences"] </li>*@
  
            </ul>
        </div>
  
        <div class="col-12 col-md-3 my-3 text-dark text-center"> 
            <h3 class="text-start text-uppercase fw-bold  text-center">@localizer["Contact"] </h3>
            <ul class="list-unstyled">
                <li class="list-group-item-action text-secondary">E-SHOPE </li>
                <li class="list-group-item-action text-secondary">MANSOURA</li>
                <li class="list-group-item-action text-secondary">(20)353132424</li>
                <li class="list-group-item-action text-secondary">e-Shpe@yahoo.com</li>
            </ul> 
        </div> </div>
</footer> 
 

Jumia_MVC/Views/Shared/_header.cshtml
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer;

<style>
    header{
        
    }
    nav{
        font-size:15px;
        align-items:center;
        position: sticky;
        top:0;
        z-index:1;
    }
    #navbar{
        background-color:#faf8f8;
    }
    .navbar li {
        list-style:none;
        padding:0 10px;
        position:relative;
        padding-top:5px;
    }
    .navbar li a{
        text-decoration:none;
        font-size:16px;
        font-weight:750;
        color:#1a1a1a;
        transition:0.3s ease;
    }
    .navbar li a::after{
        transition:0.3s ease;
    }
    .navbar li a:hover,
    .navbar li a.active{
        color:#f68b1e;
    }
    .navbar li a.active::after,
    .navbar li a:hover::after{
        content:"";
        width:40%;
        height:3px;
        background:#f68b1e;
        position:absolute;
        bottom:-4px;
        left:20px;
    }
    .bi-cart4:hover{
        color:#f68b1e;
    }
    .form-control:focus {
        box-shadow: none;
    }
    .form-control1 {
    border: 0;
    border-bottom: 1px solid #a1a2a3;
    }

        .form-control1,
        .form-control1:focus,
        .form-control1:focus:hover {
            color: #f68b1e;
            background: none;
            outline: none;
        }

.form-control1:focus,
.form-control1:focus:hover {
    border-bottom: 3px solid #ff8d00;
}
.navbar-toggler-icon{
    color:#ff8d00;
}

</style> 

<header
    dir="@(System.Threading.Thread.CurrentThread.CurrentCulture.TextInfo.IsRightToLeft? "rtl" : "ltr")">
    <nav id="navbar" class="navbar navbar-expand-lg navbar-toggleable-lg fixed-top justify-content-between">
        <div class="container-fluid">
            <a class="navbar-brand text-start text-uppercase text-dark fw-bold" asp-area="" asp-controller="Home" asp-action="Index">
                <img src="~/image/logo.png" />
                <span class="mx-1" style="color:#f68b1e;">E-</span>SHOPE</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"><i class="fa-solid fa-align-justify"></i></span>
            </button>
            <div class="navbar-collapse collapse d-lg-inline-flex justify-content-end">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="" asp-area="" asp-controller="Product" asp-action="Index">@localizer["Product"] </a>
                    </li>
                    <li class="nav-item">
                        <a class="" asp-area="" asp-controller="Favorite" asp-action="Favorite" >@localizer["Favourit"] </a>
                    </li>
                    <li class="nav-item">
                        <a class="" asp-area="" asp-controller="ContactUs"  asp-action="Index" >@localizer["ContactUs"] </a>
                    </li>
                    <li class="nav-item">
                        <a class="" asp-area="" asp-controller="About" asp-action="Index" >@localizer["About"] </a>
                    </li>   
                    <li class="nav-item" style="padding-top:1px;" >
                        <partial name="_Culture"/> 
                    </li>
                   
                </ul>

                <form class="form-inline my-2 my-lg-0" asp-controller="Product" asp-action="Filter" style="padding-right: 25px;">
                    <input name="searchString" value="@TempData["serch"]" type="text" class="form-control form-control1" placeholder=@localizer["search"]>
@*                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="bi bi-search"></i></button>
*@              </form>

                @if (!User.Identity.IsAuthenticated)
                {
                    <ul class="nabar-nav"  style="margin-top:8px;">
                        <div class="nav-item px-3 py-1">
                            <a  class="nav-link text-dark btn btn-outline-light position-relative " 
                                asp-controller="Orders" asp-action="ShoppingCart">
                                <i class="bi bi-cart4"></i>
                                <span  class="position-absolute top-0 py-1 start-100 translate-middle badge rounded-pill bg-danger">
                                    <span >0</span>

                                    <span class="visually-hidden">unread messages</span>
                                </span>

                            </a>
                        </div>  
                    </ul>
                }
                else
                {
                    <ul class="nabar-nav"  style="margin-top:8px;">
                        <div class="nav-item px-3 py-1">
                            <a  class="nav-link text-dark btn btn-outline-light position-relative " 
                              asp-controller="Orders" asp-action="ShoppingCart">
                            <i class="bi bi-cart4"></i>
                             <span  class="position-absolute top-0 py-1 start-100 translate-middle badge rounded-pill bg-danger">
                                <span id="showcount">0</span>

                                <span class="visually-hidden">unread messages</span>
                            </span>

                            </a>
                        </div>  
                    </ul>
                }
@*                        @await Component.InvokeAsync("ShoppingCatSummary")
*@                    
                     @*user profile section*@

                  
                  @*   <div class="dropdown">
                    <a class="btn btn-outline-success dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                             Hello User  </a>

                  <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                  <li><a class="dropdown-item"asp-controller="Orders" asp-action="Index">
                     <i class="bi bi-list"></i> Orders
                     </a>
                       </li>
                           </ul>
                     </div>*@

                <partial name="IdentityView.cshtml" />
            </div>
        </div>
    </nav>
</header>