Jumia_MVC/Controllers/FavoriteController.cs
namespace Jumia_MVC.Controllers
{
    public class FavoriteController : Controller
    {
        private readonly IProductsService _productsService;
        private readonly FavoriteProduct _favorite;
        public FavoriteController(IProductsService productsService, FavoriteProduct favorite)
        {
            _productsService = productsService;
            _favorite = favorite;
        }
        [MyAuthorize]
        public IActionResult Favorite()
        {
            var items = _favorite.GetFavoriteItems();
            _favorite.FavoriteItems = items;
            var response = new FavoriteVM()
            {
                Favorite = _favorite,
            };

            return View(response);
        }
        [MyAuthorize]
        public async Task<RedirectToActionResult> AddItemToFavorite(int id)
        {
            var item = await _productsService.GetProductByIdAsync(id);
            if (item != null)
            {
                _favorite.AddItemToFavorite(item);
                //item.in_favorites = true;
            }
            return RedirectToAction(nameof(Favorite));
        }

        public async Task<IActionResult> RemoveItemFromFavorite(int id)
        {
            var item = await _productsService.GetProductByIdAsync(id);
            if (item != null)
            {
                _favorite.RemoveItemFromFavorite(item);
                //item.in_favorites = false;
            }
            return RedirectToAction(nameof(Favorite));
        }
    }
}

Jumia_MVC/Views/Favorite/Favorite.cshtml
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer;

@using Jumia_MVC.Data.ViewModel
@using Jumia_MVC.Controllers
@model FavoriteVM

@{
    ViewData["Title"] = localizer["title"] ;
}
<style>
   .item{
        box-shadow:3px 3px 5px lightgray;
        background-color:white;
        border-radius:5px;
    }
    .item{
        height:150px;
        border:1px solid lightgray;
        padding-top:10px;

    }
    .btn{
        font-weight:bold;
    }
    .b2 {
    color: #f68b1e;
}

    .b2:hover {
        background-color: #feefde;
        color: #f68b1e;
    }

.b1 {
    background-color: #f68b1e;
    color: white;
    box-shadow: 3px 3px 5px lightgray;
}

    .b1:hover {
        color: #f68b1e;
        background-color: white;
    }
    .card-img-top {
        height:97%;
        padding-left:3px;
    }
    
</style>


<div class="row mt-5 g-0 m-0">
    <div class=" col-9 offset-2 main">
        <div style="padding-top:100px"
        dir="@(System.Threading.Thread.CurrentThread.CurrentCulture.TextInfo.IsRightToLeft? "rtl" : "ltr")">
            <h2>@localizer["title2"] </h2><hr />
        </div>
        @if (Model.Favorite.FavoriteItems.Count()==0)
{
      <pre>
      </pre>
        <div class="text-center">
            <img src="data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' width='100' height='100'%3e%3cdefs%3e%3cpath id='a' d='M99.962 49.908c0 27.564-22.378 49.908-49.981 49.908C22.377 99.816 0 77.472 0 49.908S22.377 0 49.98 0c27.604 0 49.982 22.344 49.982 49.908'/%3e%3c/defs%3e%3cg fill='none' fill-rule='evenodd'%3e%3cmask id='b' fill='white'%3e%3cuse xlink:href='%23a'/%3e%3c/mask%3e%3cuse fill='%23F5F5F5' xlink:href='%23a'/%3e%3cg fill-rule='nonzero' mask='url(%23b)'%3e%3cpath fill='%23F68B1E' d='M61.496 29A12.01 12.01 0 0 0 51 35.127v35.83c3.38-2.511 22.5-17.287 22.5-30.082C73.5 34.317 68.125 29 61.496 29z'/%3e%3cpath fill='%23FFB048' d='M40.004 29C33.374 29 28 34.317 28 40.875c0 12.794 19.12 27.57 22.5 30.082v-35.83A12.011 12.011 0 0 0 40.004 29z'/%3e%3c/g%3e%3c/g%3e%3c/svg%3e"
            alt=""><pre>
            </pre>
            <h3>@localizer["noItem"]<pre></pre></h3>
            <h5 class="col-8 offset-2" 
                dir="@(System.Threading.Thread.CurrentThread.CurrentCulture.TextInfo.IsRightToLeft? "rtl" : "ltr")">@localizer["findSomeThing"] <pre>
            </pre></h5>
            <a class="btn b1" asp-controller="Product" asp-action="Index"  >@localizer["continue"] </a>
        </div>
    
}else{
        <div class="favitem"
            dir="@(System.Threading.Thread.CurrentThread.CurrentCulture.TextInfo.IsRightToLeft? "rtl" : "ltr")">
            @foreach (var item in Model.Favorite.FavoriteItems)
                {
                    <div class="item d-flex">
                        <a asp-controller="Product" asp-action="Details" asp-route-id="@item.Product.Id" class="align-middle col-2"><img src="@item.Product.Image" class="card-img-top img-fluid rounded" @*style="height:100px"*@ /></a> 
                        <div class="align-middle col-6 p-2" ><div class="text-truncate"> @item.Product.Name<pre>
                        </pre></div>
                        <div class="styleprice align-middle"><p class="card-text text-muted ">@item.Product.Price.ToString("c", new System.Globalization.CultureInfo("en-US"))</p>
                                    @if (item.Product.Discount != 0)
                                    {
                                        <p class="card-text text-danger text-decoration-line-through">
                                            @item.Product.Old_Price.ToString("c", new System.Globalization.CultureInfo("en-US"))
                                        </p>
                                    }
                                    else
                                    {
                                        <p></p>
                                    }
                            </div>
                        </div>
                        <div class="align-middle col-md-1"></div>
                        <div>
                            <div class="btn-group">
                                    <a class="btn b1 addItemInCard" onclick="AddItemINCard(@item.Product.Id)"  >
                                        <i class="fas fa-cart-plus"><partial></i><span> @localizer["add"]</span>
                                    </a>
                                
                                </div>
                            <pre>
                            </pre>
                      @*  <div class="align-middle">
                                <div class="btn-group">*@
                                    <a class="btn b2" asp-controller="Favorite" asp-action="RemoveItemFromFavorite" asp-route-id="@item.Product.Id" data-id="@item.Product.Id" >
                                       <i class="bi bi-trash"></i><span>@localizer["Remove"]</span></a>
                                
                                </div>
                        </div> 
                        @*</div>
                        </div>*@
                        <hr />
                }
       </div>
       
       

        <div class="text-center">
            <div class="btn-group">
                <a class="btn b1" asp-controller="Product" asp-action="Index">
                   @localizer["continue"]
                </a>
            </div>
        </div>
    
        }
        </div>
        </div>


@section Scripts{
    <script >
          $('.remove-fvourit').on('click', function () {
                                var btn= $(this);

                $.ajax({
        url: '/api/FavouritApi/' +btn.data('id'),
        method: "delete",
        success: function (data) {
                       btn.parents('tr').fadeOut();

       

            swal({
                title: "Done",
                text: "Product Delete From Favourit",
                icon: "success",
                button: "Ok",
            });
            // this.parents('tr').fadeOut();

        },
        errot: function () {
            alert("Some thing with wrong");
        }

    });
          });
   </script>
        }